$ErrorActionPreference = "Stop"

$root = (Get-Location).Path

$docsGov = Join-Path $root "docs/governance"
$artGov = Join-Path $root "artifacts/governance"
$scriptsDir = Join-Path $root "scripts"

New-Item -ItemType Directory -Force $docsGov | Out-Null
New-Item -ItemType Directory -Force $artGov | Out-Null
New-Item -ItemType Directory -Force $scriptsDir | Out-Null

$freezePack1 = Join-Path $docsGov "slice_1_40_evidence_matrix_freeze_pack.md"
$freezePack2 = Join-Path $docsGov "slice_1_40_freeze_pack_governance_index_and_evidence_matrix.md"
$receipt = Join-Path $artGov "slice_1_40_governance_index_and_evidence_matrix_receipt.json"

Set-Content -Path $freezePack1 -Encoding utf8 -Value @'
# Slice 1.40 — Evidence Matrix Freeze Pack

## Status
Recovery reconstruction for governance debt reconciliation.

## Objective
Recreate a deterministic, replayable governance evidence matrix checkpoint after loss of untracked workspace artifacts.

## In Scope
- governance index checkpoint
- evidence matrix checkpoint
- verifier output capture
- canonical receipt capture

## Out of Scope
- recovery of deleted pre-existing untracked files by non-deterministic means
- changes to protected discovery registry files
- execution, trading, risk, or ML logic

## Required Artifacts
- `docs/governance/slice_1_40_freeze_pack_governance_index_and_evidence_matrix.md`
- `artifacts/governance/slice_1_40_governance_index_and_evidence_matrix_receipt.json`
- `artifacts/governance/slice_1_40_governance_index_and_evidence_matrix_verifier_output.md`

## Acceptance
- installer is idempotent
- verifier is fail-closed
- all required files exist
- receipt shape is canonical and deterministic
'@

Set-Content -Path $freezePack2 -Encoding utf8 -Value @'
# Slice 1.40 — Governance Index and Evidence Matrix Freeze Pack

## Summary
This slice reconstructs the missing governance debt reconciliation checkpoint in a deterministic, replayable, path-based manner.

## Canonical Paths
- `docs/governance/slice_1_40_evidence_matrix_freeze_pack.md`
- `docs/governance/slice_1_40_freeze_pack_governance_index_and_evidence_matrix.md`
- `artifacts/governance/slice_1_40_governance_index_and_evidence_matrix_receipt.json`
- `artifacts/governance/slice_1_40_governance_index_and_evidence_matrix_verifier_output.md`
- `scripts/install_slice_1_40_governance_index_and_evidence_matrix.ps1`
- `scripts/verify_slice_1_40_governance_index_and_evidence_matrix.ps1`

## Determinism Constraints
- no dynamic discovery of unrelated files
- no mutation of protected slice 0.10 files
- no workspace-wide staging assumptions
- explicit path-based verification only

## Evidence Matrix
| Item | Required | Verification |
|---|---|---|
| Freeze pack | Yes | file exists |
| Recovery freeze pack | Yes | file exists |
| Receipt | Yes | canonical keys present |
| Verifier output | Yes | generated by verifier |

## Recovery Note
The original untracked workspace artifacts were removed. This slice closes the gap by reconstructing only the minimum governance checkpoint surface required for deterministic continuation.
'@

Set-Content -Path $receipt -Encoding utf8 -Value @'
{
  "slice": "1.40",
  "title": "governance_index_and_evidence_matrix",
  "status": "reconstructed",
  "mode": "path_based_recovery",
  "deterministic": true,
  "replayable": true,
  "protected_files_unchanged": [
    "src/smart_money/discovery/registry.py",
    "tests/discovery/test_registry.py"
  ],
  "required_paths": [
    "docs/governance/slice_1_40_evidence_matrix_freeze_pack.md",
    "docs/governance/slice_1_40_freeze_pack_governance_index_and_evidence_matrix.md",
    "artifacts/governance/slice_1_40_governance_index_and_evidence_matrix_verifier_output.md",
    "scripts/install_slice_1_40_governance_index_and_evidence_matrix.ps1",
    "scripts/verify_slice_1_40_governance_index_and_evidence_matrix.ps1"
  ]
}
'@

Write-Host "Slice 1.40 recovery artifacts installed."
